all:
	$(MAKE) -C common all
	$(MAKE) -C log all
	$(MAKE) -C gpio all
	$(MAKE) -C jxjcam all
	$(MAKE) -C xzcam all
clean:
	$(MAKE) -C common clean
	$(MAKE) -C log clean
	$(MAKE) -C gpio clean
	$(MAKE) -C jxjcam clean
	$(MAKE) -C xzcam clean
rebuilt:clean all
